### PR TITLE
eslint env es2017, @kintone/kintone-ui-component: ^0.4.0 > ^0.6.0, @kintone/kintone-js-sdk > @kintone/rest-api-client: ^1.0.0

### PR DESCRIPTION
**Pull request by r3-yamauchi**
- eslint env es2017 to use async/await
- @kintone/kintone-ui-component: ^0.4.0 > ^0.6.0
- @kintone/kintone-js-sdk > @kintone/rest-api-client: ^1.0.0
- webpack.config performance: maxEntrypointSize, maxAssetSize
- webpack 'mode' option has not been set, webpack will fallback to 'production' for this value. https://webpack.js.org/configuration/mode/
- add renovate.json

### CODE REVIEW

**Comment by youtr-s** [comment]
Thank you for PR!
We would like to merge your PR except about  [@kintone/kintone-js-sdk > @kintone/rest-api-client: ^1.0.0] because rest-api-client does not fully support kintone-js-sdk's functions.
Is it OK?

**Comment by r3-yamauchi** [comment]
> except about [@kintone/kintone-js-sdk > @kintone/rest-api-client: ^1.0.0] 

I think it's OK

> because rest-api-client does not fully support kintone-js-sdk's functions.

What features does @kintone/rest-api-client not support?
Does @kintone/rest-api-client have a roadmap?

**Comment by zaki-yama** [comment]
@r3-yamauchi 
We're sorry for our late reply.
Here's the list of features that rest-api-client doesn't currently support.
(The list is ordered in priority we consider now)

- add/update/delete multiple (over 100) records ( [`xxxAllRecords()`](https://kintone.github.io/kintone-js-sdk/latest/reference/record/#addallrecordsparams) )
- upsert record(s) ( [`upsertRecord()`](https://kintone.github.io/kintone-js-sdk/latest/reference/record/#upsertrecordparams) & [`upsertRecords()`](https://kintone.github.io/kintone-js-sdk/latest/reference/record/#upsertrecordsparams) )
- support client certificate
- support OAuth header (https://github.com/kintone/js-sdk/issues/64)
- support Proxy server settings

We'll support them in a few months (2-3 months, if possible).
Also, we'll release each feature soon after it is finished.

> Does @kintone/rest-api-client have a roadmap?

Sorry, not yet. But we're planning to publish it.
We hope you can wait for a couple of weeks.

**Comment by youtr-s** [comment]
@r3-yamauchi 
> except about [@kintone/kintone-js-sdk > @kintone/rest-api-client: ^1.0.0]
>I think it's OK
Is it ok to modify your PR by ourselves ?

**Comment by youtr-s** [comment]
@r3-yamauchi 
>except about [@kintone/kintone-js-sdk > @kintone/rest-api-client: ^1.0.0]
>I think it's OK

Is it ok to modify your PR by ourselves ?

**Comment by r3-yamauchi** [comment]
@youtr-s 
> Is it ok to modify your PR by ourselves ?

it's OK!!!!!!!!!!

**Comment by youtr-s** [comment]
@r3-yamauchi 
Thanks for your contribution.
We released [kintone-cli v0.1.4](https://github.com/kintone/kintone-cli/releases/tag/v0.1.4) include your PR.
Please check it.
Thank you.

**Pull request merged**
